### ISSUE TITLE
Add Stylish Shadows Classes

### ISSUE THREAD

**Issue by ghost** [alcapitan/atui#126]
First, make sure your idea is useful, it relates to this directory, and it has never been suggested.

1. Shadows Classes Decreases Time to write shadow for each element 
2. i have written the code just accept the pr

**Comment by alcapitan** [comment]
Hello,

I looked at your pull request but I thought your shadow stylesheet was heavy.
I would not like to present 40 different styles to the user, he can be lost with the choise.

However, I wanted to take your idea, so I made a commit d7ae1ea73614dd0ebe0b082ed4998eb12434732a that create a css shadow light medium heavy variable.

By the way, the other reason that prevented me from accepting your pull request is that your code doesn't follow my homogeneous style and organization.
Indeed, this is normal because I am the only one who knows the science of my code.
I will make a good documentation at the end of the development.

I thank you anyway for your participation,

**Comment by ghost** [comment]
Ok , Understand.
